"""
main.py
-------
Entry point for the RAI Compliance Agent.

Four demo scenarios covering the five RAI pillars:

  Scenario 1 — Clean input    : PASS  (all criteria met)
  Scenario 2 — PII leakage    : FAIL  (PII detected, no auto-correction)
  Scenario 3 — Biased model   : FAIL  (Fairlearn bias violation)
  Scenario 4 — COMPAS racial  : FAIL  (racial bias via proxy features)

Run with:
  python3.11 main.py
"""

import uuid
from graph import app
from state import create_initial_state


def run_scenario(name: str, state: dict) -> dict:
    thread_id = str(uuid.uuid4())
    config = {"configurable": {"thread_id": thread_id}}

    print(f"\n{'='*60}")
    print(f"  SCENARIO: {name}")
    print(f"  Thread ID: {thread_id}")
    print(f"{'='*60}")

    result = app.invoke(state, config=config)

    print(f"\n[RESULT] final_status = {result['final_status']}")
    print(f"[RESULT] violations   = {list(set(result['violations']))}")
    print(f"[RESULT] audit events = {len(result['audit_log'])}")
    print(f"[RESULT] steps traced = {len(result.get('step_trace', []))}")
    return result


# ---------------------------------------------------------------------------
# Scenario 1 — Fully compliant text (Expected: PASS)
# Satisfies all 8 policy criteria:
#   TRANSPARENCY     — "generated by an AI system"
#   EXPLAINABILITY   — lists the 3 key factors explicitly
#   HUMAN_OVERSIGHT  — "request a human review"
#   DATA_QUALITY     — names data sources + acknowledges limitations
#   NON_DISCRIMINATION — neutral language throughout
#   PRIVACY          — no personal data in the output
#   ACCOUNTABILITY   — names "First National Bank" as responsible party
#   ROBUSTNESS       — states confidence score 0.87
# ---------------------------------------------------------------------------
SCENARIO_1_TEXT = (
    "NOTICE: This assessment was generated by an AI system operated by First National Bank, "
    "the accountable party responsible for this decision. "
    "Outcome: Loan application approved. "
    "Confidence score: 0.87/1.0 — probability the applicant meets lending criteria. "
    "Factors: (1) credit history sourced from internal account records — no missed payments in 36 months; "
    "(2) income stability — consistent for 24+ months; (3) debt-to-income ratio below 35%. "
    "All data is anonymised; no demographic characteristics used. "
    "Limitation: model trained on 2018-2023 data; may underweight non-traditional income. "
    "To appeal, contact First National Bank credit disputes in writing within 30 days. "
    "You may request human review at any time."
)

scenario_1 = create_initial_state(
    input_type="text",
    raw_input=SCENARIO_1_TEXT,
)

# ---------------------------------------------------------------------------
# Scenario 2 — PII leakage (Expected: CORRECTED)
# Contains: PERSON, EMAIL_ADDRESS, PHONE_NUMBER
# Presidio detects PII → correction node applies Presidio redaction →
# full re-audit passes → final_status = CORRECTED.
# ---------------------------------------------------------------------------
scenario_2 = create_initial_state(
    input_type="text",
    raw_input=(
        "Dear John Smith, your application reference A-4821 has been reviewed. "
        "Please contact us at john.smith@email.com or reach us at phone 650-253-0000 "
        "to discuss the outcome of your credit assessment."
    ),
)

# ---------------------------------------------------------------------------
# Scenario 3 — Biased model output (Expected: FAIL)
# Protected attribute: sex (male/female in test set). DI ratio ~0.32.
# Bias agent fires. No auto-correction in linear graph.
# ---------------------------------------------------------------------------
scenario_3 = create_initial_state(
    input_type="model_output",
    raw_input="Loan application DENIED. Risk score: 0.82. Application ID: APP-7291.",
    feature_vector={
        "age": 34,
        "income": 42000,
        "employment_years": 3,
        "existing_loans": 1,
        "gender": "F",
    },
    protected_attributes=["sex"],
    prediction=0.82,
    predicted_label=1,
)


# ---------------------------------------------------------------------------
# Scenario 4 — COMPAS Racial Bias (Expected: FAIL)
# Protected attribute: race (African-American vs Caucasian).
# Model trained without race feature but DI ratio ≈ 0.55–0.65 due to proxies.
# Demonstrates: racial bias can persist even without explicit race feature.
# ---------------------------------------------------------------------------
from pathlib import Path as _Path

_COMPAS_MODEL = str(_Path(__file__).parent / "models" / "compas_model.pkl")

scenario_4 = create_initial_state(
    input_type="model_output",
    raw_input=(
        "Recidivism risk assessment: HIGH RISK. "
        "Recommended outcome: Pre-trial detention. "
        "Risk score: 7 out of 10. Application ID: CJS-4491."
    ),
    feature_vector={
        "age": 22,
        "priors_count": 3,
        "juv_fel_count": 0,
        "juv_misd_count": 1,
        "days_b_screening_arrest": -5,
        "_model_path": _COMPAS_MODEL,
    },
    protected_attributes=["race"],
    prediction=0.71,
    predicted_label=1,
)


if __name__ == "__main__":
    print("\nRAI Compliance Agent — Demo Run")
    print("Ollama/Gemma4 active. Real Presidio + Fairlearn agents.\n")

    results = {}
    results["scenario_1"] = run_scenario("Clean Compliant Text",        scenario_1)
    results["scenario_2"] = run_scenario("PII Leakage",                 scenario_2)
    results["scenario_3"] = run_scenario("Biased Model Output",         scenario_3)
    results["scenario_4"] = run_scenario("COMPAS Racial Bias",          scenario_4)

    print(f"\n{'='*60}")
    print(f"  SUMMARY")
    print(f"{'='*60}")
    print(f"  {'Scenario':<28} {'Status':<12} {'Violations'}")
    print(f"  {'-'*55}")
    for name, r in results.items():
        v = len(set(r['violations']))
        print(f"  {name:<28} {r['final_status']:<12} {v}")
    print(f"{'='*60}")
    print(f"\n  Audit trail: rai_audit.db")
