"""
validate_demo.py
----------------
Runs each of the 3 demo scenarios N times and reports:
  - Pass rate per scenario
  - Flaky runs (unexpected outcomes)
  - Timing statistics (mean / min / max per scenario)

Usage:
  python validate_demo.py              # 20 runs each (default)
  python validate_demo.py --runs 5     # faster smoke check
  python validate_demo.py --runs 20 --scenario 1   # single scenario only

Results are written to: validation_report.txt
"""

import argparse
import time
import uuid
from datetime import datetime
from pathlib import Path

from graph import app
from state import create_initial_state

# ---------------------------------------------------------------------------
# Scenario definitions
# ---------------------------------------------------------------------------

SCENARIO_1_TEXT = (
    "NOTICE: This assessment was generated by an AI system operated by First National Bank, "
    "the accountable party responsible for this decision. "
    "Outcome: Loan application approved. "
    "Confidence score: 0.87/1.0 — probability the applicant meets lending criteria. "
    "Factors: (1) credit history sourced from internal account records — no missed payments in 36 months; "
    "(2) income stability — consistent for 24+ months; (3) debt-to-income ratio below 35%. "
    "All data is anonymised; no demographic characteristics used. "
    "Limitation: model trained on 2018-2023 data; may underweight non-traditional income. "
    "To appeal, contact First National Bank credit disputes in writing within 30 days. "
    "You may request human review at any time."
)

SCENARIO_2_TEXT = (
    "Dear John Smith, your application reference A-4821 has been reviewed. "
    "Please contact us at john.smith@email.com or call 650-253-0000 "
    "to discuss the outcome of your assessment."
)

SCENARIO_3_TEXT = "Loan application DENIED. Risk score: 0.82. Application ID: APP-7291."
SCENARIO_3_FEATURES = {
    "age": 34, "income": 42000, "employment_years": 3,
    "existing_loans": 1, "gender": "F",
}

SCENARIOS = {
    1: {
        "name": "Clean Compliant Text",
        "expected_status": {"PASS"},
        "expected_violations_include": set(),
        "expected_violations_exclude": {"PII_DETECTED", "BIAS_DETECTED"},
        "state_kwargs": {
            "input_type": "text",
            "raw_input": SCENARIO_1_TEXT,
        },
    },
    2: {
        "name": "PII Leakage",
        "expected_status": {"FAIL"},
        "expected_violations_include": {"PII_DETECTED"},
        "expected_violations_exclude": set(),
        "state_kwargs": {
            "input_type": "text",
            "raw_input": SCENARIO_2_TEXT,
        },
    },
    3: {
        "name": "Biased Model Output",
        "expected_status": {"FAIL"},
        "expected_violations_include": {"BIAS_DETECTED"},
        "expected_violations_exclude": set(),
        "state_kwargs": {
            "input_type": "model_output",
            "raw_input": SCENARIO_3_TEXT,
            "feature_vector": SCENARIO_3_FEATURES,
            "protected_attributes": ["sex"],
            "prediction": 0.82,
            "predicted_label": 1,
        },
    },
    4: {
        "name": "COMPAS Racial Bias",
        "expected_status": {"FAIL"},
        "expected_violations_include": {"BIAS_DETECTED"},
        "expected_violations_exclude": set(),
        "state_kwargs": {
            "input_type": "model_output",
            "raw_input": (
                "Recidivism risk assessment: HIGH RISK. "
                "Recommended outcome: Pre-trial detention. "
                "Risk score: 7 out of 10. Application ID: CJS-4491."
            ),
            "feature_vector": {
                "age": 22,
                "priors_count": 3,
                "juv_fel_count": 0,
                "juv_misd_count": 1,
                "days_b_screening_arrest": -5,
                "_model_path": str(Path(__file__).parent / "models" / "compas_model.pkl"),
            },
            "protected_attributes": ["race"],
            "prediction": 0.71,
            "predicted_label": 1,
        },
    },
}


def run_once(scenario_id: int) -> dict:
    sc = SCENARIOS[scenario_id]
    state = create_initial_state(**sc["state_kwargs"])
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}

    t0 = time.time()
    result = app.invoke(state, config=config)
    elapsed = round(time.time() - t0, 2)

    fs = result["final_status"]
    violations = set(result.get("violations", []))
    passed = (
        fs in sc["expected_status"]
        and sc["expected_violations_include"].issubset(violations)
        and not sc["expected_violations_exclude"].intersection(violations)
    )

    return {
        "scenario": scenario_id,
        "final_status": fs,
        "violations": violations,
        "elapsed": elapsed,
        "passed_expectations": passed,
    }


def run_scenario(scenario_id: int, n: int) -> dict:
    sc = SCENARIOS[scenario_id]
    print(f"\n  Scenario {scenario_id}: {sc['name']} ({n} runs)")
    print(f"  Expected status: {sc['expected_status']}")

    results = []
    for i in range(1, n + 1):
        print(f"    Run {i:2d}/{n} ... ", end="", flush=True)
        r = run_once(scenario_id)
        mark = "✓" if r["passed_expectations"] else "✗ FLAKY"
        print(f"{r['final_status']:12} {r['elapsed']:6.1f}s  {mark}")
        results.append(r)

    pass_count = sum(1 for r in results if r["passed_expectations"])
    elapsed_vals = [r["elapsed"] for r in results]
    statuses = [r["final_status"] for r in results]
    flaky = [r for r in results if not r["passed_expectations"]]

    summary = {
        "scenario_id": scenario_id,
        "name": sc["name"],
        "total": n,
        "pass_count": pass_count,
        "pass_rate": round(pass_count / n * 100, 1),
        "statuses": statuses,
        "mean_elapsed": round(sum(elapsed_vals) / n, 1),
        "min_elapsed": round(min(elapsed_vals), 1),
        "max_elapsed": round(max(elapsed_vals), 1),
        "flaky_runs": flaky,
    }

    print(f"  → Pass rate: {pass_count}/{n} ({summary['pass_rate']}%)")
    print(f"  → Timing: mean={summary['mean_elapsed']}s  min={summary['min_elapsed']}s  max={summary['max_elapsed']}s")
    if flaky:
        print(f"  → FLAKY RUNS:")
        for f in flaky:
            print(f"       status={f['final_status']}  violations={f['violations']}")
    return summary


def write_report(summaries: list[dict], n: int, outfile: str) -> None:
    lines = []
    lines.append("=" * 65)
    lines.append("  RAI COMPLIANCE AGENT — VALIDATION REPORT")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  Runs per scenario: {n}")
    lines.append("=" * 65)

    overall_pass = sum(s["pass_count"] for s in summaries)
    overall_total = sum(s["total"] for s in summaries)
    overall_rate = round(overall_pass / overall_total * 100, 1)

    lines.append(f"\n  OVERALL PASS RATE: {overall_pass}/{overall_total} ({overall_rate}%)")
    lines.append("")

    for s in summaries:
        lines.append(f"  Scenario {s['scenario_id']}: {s['name']}")
        lines.append(f"    Pass rate : {s['pass_count']}/{s['total']} ({s['pass_rate']}%)")
        lines.append(f"    Timing    : mean={s['mean_elapsed']}s  min={s['min_elapsed']}s  max={s['max_elapsed']}s")
        from collections import Counter
        status_dist = Counter(s["statuses"])
        lines.append(f"    Statuses  : {dict(status_dist)}")
        if s["flaky_runs"]:
            lines.append(f"    FLAKY     : {len(s['flaky_runs'])} run(s)")
            for f in s["flaky_runs"]:
                lines.append(f"      → {f['final_status']}  violations={f['violations']}")
        lines.append("")

    lines.append("=" * 65)
    report = "\n".join(lines)
    print(report)

    with open(outfile, "w") as fh:
        fh.write(report + "\n")
    print(f"\n  Report saved → {outfile}")


def main():
    parser = argparse.ArgumentParser(description="Run demo scenarios N times each.")
    parser.add_argument("--runs", type=int, default=20, help="Runs per scenario (default: 20)")
    parser.add_argument("--scenario", type=int, choices=[1, 2, 3, 4], default=None,
                        help="Run a single scenario only")
    args = parser.parse_args()

    scenario_ids = [args.scenario] if args.scenario else [1, 2, 3, 4]

    print(f"\nRAI Compliance Agent — Demo Validation")
    print(f"Scenarios: {scenario_ids}   Runs each: {args.runs}")

    summaries = []
    for sid in scenario_ids:
        summary = run_scenario(sid, args.runs)
        summaries.append(summary)

    write_report(summaries, args.runs, "validation_report.txt")


if __name__ == "__main__":
    main()
