"""
nodes/correction.py
-------------------
Self-Correction Node — Ollama/Gemma LLM implementation.

When any auditor agent flags a violation, the conditional edge routes here.
This node produces a corrected version of current_text, increments
correction_count, resets agent results, and routes back to the PII agent
so the full audit chain re-runs on the corrected text.

PII violations use Presidio redacted_text directly (no LLM needed).
All other violations use a targeted LLM prompt.
"""

from datetime import datetime, timezone
from langchain_ollama import ChatOllama
from state import ComplianceState

OLLAMA_MODEL = "gemma4:latest"

CORRECTION_PROMPTS = {
    "BIAS_DETECTED": """The following AI output has been flagged for algorithmic bias.
Disparate impact ratio: {di_ratio:.2f} (legal threshold: 0.8).

ORIGINAL TEXT:
\"\"\"{text}\"\"\"

Rewrite the text to be neutral with respect to protected characteristics
(gender, age, race, religion, disability). Do not reference or imply any
demographic group. Preserve the factual content. Return ONLY the corrected text.""",

    "POLICY_TRANSPARENCY": """The following AI-generated text does not disclose that it was produced by AI,
violating EU AI Act Article 50.

ORIGINAL TEXT:
\"\"\"{text}\"\"\"

Add a brief disclosure that this content was generated by an AI system.
Place it at the end. Return ONLY the corrected text.""",

    "POLICY_EXPLAINABILITY": """The following AI decision output lacks explanation, violating EU AI Act Article 13.

ORIGINAL TEXT:
\"\"\"{text}\"\"\"

Add a plain-language explanation (max 2 sentences) of the key factors that
led to this outcome. Return ONLY the corrected text.""",

    "POLICY_HUMAN_OVERSIGHT": """The following text provides no mechanism for human review, violating EU AI Act Article 14.

ORIGINAL TEXT:
\"\"\"{text}\"\"\"

Add one sentence informing the recipient they may request a human review
of this decision. Return ONLY the corrected text.""",

    "DEFAULT": """The following AI-generated text has a compliance violation: {violation_id}.

ORIGINAL TEXT:
\"\"\"{text}\"\"\"

Rewrite the text to address the violation while preserving the original meaning.
Return ONLY the corrected text.""",
}


def _detect_active_violation(state: ComplianceState) -> str:
    """
    Derives which violation to fix when active_violation is not set.
    Priority: PII > Bias > highest-severity Policy violation.
    """
    if explicit := state.get("active_violation"):
        return explicit
    pii = state.get("pii_result") or {}
    if not pii.get("passed", True):
        return "PII_DETECTED"
    bias = state.get("bias_result") or {}
    if not bias.get("passed", True):
        return "BIAS_DETECTED"
    policy = state.get("policy_result") or {}
    violations = policy.get("violations", [])
    if violations:
        severity_order = {"high": 0, "medium": 1, "low": 2}
        worst = sorted(violations, key=lambda v: severity_order.get(v.get("severity", "low"), 2))[0]
        return f"POLICY_{worst['id']}"
    return "UNKNOWN"


def correction_node(state: ComplianceState) -> dict:
    """
    Attempts to auto-correct the active violation.
    Increments correction_count and resets agent results so auditors re-run.
    """
    violation = _detect_active_violation(state)
    count = state["correction_count"] + 1

    print(f"\n[CORRECTION] Attempting fix for: {violation}")
    print(f"[CORRECTION] Correction attempt #{count} of {state['max_corrections']}")

    corrected_text = _attempt_correction(state, violation)

    changed = corrected_text != state["current_text"]
    print(f"[CORRECTION] Text {'changed' if changed else 'UNCHANGED — LLM returned same text'}. Re-entering audit chain.")

    log_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "node": "correction",
        "action": "AUTO_CORRECTION",
        "result": "attempted",
        "detail": {
            "violation": violation,
            "attempt_number": count,
            "original_length": len(state["current_text"]),
            "corrected_length": len(corrected_text),
            "text_changed": changed,
        },
        "correction_count": count,
    }

    return {
        "current_text": corrected_text,
        "correction_count": count,
        "active_violation": None,
        "pii_result": None,
        "bias_result": None,
        "policy_result": None,
        "current_node": "correction",
        "audit_log": [log_entry],
    }


def _attempt_correction(state: ComplianceState, violation: str) -> str:
    """
    For PII: use Presidio-redacted text directly (deterministic, no LLM).
    For all other violations: call Ollama/Gemma with targeted prompt.
    """
    # PII correction — use Presidio output directly, no LLM needed
    if violation == "PII_DETECTED":
        pii = state.get("pii_result") or {}
        redacted = pii.get("redacted_text")
        if redacted:
            print("[CORRECTION] Using Presidio redaction directly (no LLM).")
            return redacted
        # Fallback if redacted_text not populated
        print("[CORRECTION] No redacted_text in pii_result — falling back to LLM.")

    llm = ChatOllama(model=OLLAMA_MODEL, temperature=0)
    prompt = _build_correction_prompt(state, violation)

    try:
        response = llm.invoke(prompt)
        corrected = response.content.strip()
        # Strip any markdown fences the model may add
        if corrected.startswith("```"):
            lines = corrected.split("\n")
            corrected = "\n".join(
                l for l in lines if not l.startswith("```")
            ).strip()
        if corrected and corrected != state["current_text"]:
            return corrected
        print("[CORRECTION] LLM returned unchanged text.")
        return state["current_text"]
    except Exception as e:
        print(f"[CORRECTION] LLM call failed: {e}. Returning original.")
        return state["current_text"]


def _build_correction_prompt(state: ComplianceState, violation: str) -> str:
    text = state["current_text"]

    if violation == "BIAS_DETECTED" and state.get("bias_result"):
        di_ratio = state["bias_result"].get("disparate_impact_ratio") or 0.0
        return CORRECTION_PROMPTS["BIAS_DETECTED"].format(text=text, di_ratio=di_ratio)

    template_key = violation if violation in CORRECTION_PROMPTS else "DEFAULT"
    return CORRECTION_PROMPTS[template_key].format(
        text=text,
        violation_id=violation,
    )
