"""
tests/test_policy_agent.py
---------------------------
Unit tests for the Policy Compliance Agent (Ollama/Gemma-backed).

Run with: python -m pytest tests/test_policy_agent.py -v
Requires: ollama running with gemma4:latest pulled
"""

import sys
from pathlib import Path

import pytest

sys.path.append(str(Path(__file__).parent.parent))

from state import create_initial_state
from nodes.policy_agent import policy_agent_node


def _run(text: str) -> dict:
    state = create_initial_state(input_type="text", raw_input=text)
    return policy_agent_node(state)


CLEAN_TEXT = (
    "NOTICE: This assessment was generated by an AI system operated by First National Bank, "
    "the accountable party responsible for this decision. "
    "Outcome: Loan application approved. "
    "Confidence score: 0.87/1.0 — probability the applicant meets lending criteria. "
    "Factors: (1) credit history sourced from internal account records — no missed payments in 36 months; "
    "(2) income stability — consistent for 24+ months; (3) debt-to-income ratio below 35%. "
    "All data is anonymised; no demographic characteristics used. "
    "Limitation: model trained on 2018-2023 data; may underweight non-traditional income. "
    "To appeal, contact First National Bank credit disputes in writing within 30 days. "
    "You may request human review at any time."
)

NO_AI_DISCLOSURE = (
    "Your loan application has been denied. Our assessment found your risk profile "
    "to be above acceptable thresholds."
)

NO_EXPLANATION = (
    "This is an AI-generated notification. Your application has been rejected."
)

NO_HUMAN_OVERSIGHT = (
    "This AI system has denied your loan application. This decision is automated "
    "and final. No further review is available."
)

DISCRIMINATORY = (
    "Due to your demographic background and marital status, the application "
    "was declined. Female applicants in this category present higher risk."
)


def test_clean_text_passes():
    """Well-formed text with AI disclosure + human review option should pass."""
    result = _run(CLEAN_TEXT)
    pr = result["policy_result"]
    # LLM may find minor issues — check no high-severity violations
    high_violations = [v for v in pr["violations"] if v["severity"] == "high"]
    assert len(high_violations) == 0, f"Unexpected high violations: {high_violations}"


def test_no_ai_disclosure_flags_transparency():
    """Text with no AI disclosure should flag TRANSPARENCY."""
    result = _run(NO_AI_DISCLOSURE)
    violation_ids = [v["id"] for v in result["policy_result"]["violations"]]
    assert "TRANSPARENCY" in violation_ids, f"Expected TRANSPARENCY, got: {violation_ids}"


def test_no_explanation_flags_explainability():
    """Text with AI disclosure but no explanation should flag EXPLAINABILITY."""
    result = _run(NO_EXPLANATION)
    violation_ids = [v["id"] for v in result["policy_result"]["violations"]]
    assert "EXPLAINABILITY" in violation_ids, f"Expected EXPLAINABILITY, got: {violation_ids}"


def test_no_human_oversight_flagged():
    """Text explicitly denying human review should flag HUMAN_OVERSIGHT."""
    result = _run(NO_HUMAN_OVERSIGHT)
    violation_ids = [v["id"] for v in result["policy_result"]["violations"]]
    assert "HUMAN_OVERSIGHT" in violation_ids, f"Expected HUMAN_OVERSIGHT, got: {violation_ids}"


def test_discriminatory_language_flagged():
    """Text with discriminatory language should flag NON_DISCRIMINATION."""
    result = _run(DISCRIMINATORY)
    violation_ids = [v["id"] for v in result["policy_result"]["violations"]]
    assert "NON_DISCRIMINATION" in violation_ids, f"Expected NON_DISCRIMINATION, got: {violation_ids}"


def test_policy_result_schema():
    """Policy result must conform to the API contract."""
    result = _run(CLEAN_TEXT)
    pr = result["policy_result"]
    assert "violations" in pr
    assert "passed" in pr
    assert "severity" in pr
    assert "summary" in pr
    assert isinstance(pr["violations"], list)
    assert pr["severity"] in ("none", "low", "medium", "high")
    for v in pr["violations"]:
        for key in ["id", "description", "severity", "article_reference", "remediation"]:
            assert key in v, f"Missing key '{key}' in violation: {v}"


def test_violations_only_known_ids():
    """LLM must not hallucinate criterion IDs not in POLICY_CRITERIA."""
    from nodes.policy_agent import VALID_IDS
    result = _run(NO_AI_DISCLOSURE)
    for v in result["policy_result"]["violations"]:
        assert v["id"] in VALID_IDS, f"Unknown violation ID: {v['id']}"


def test_audit_log_entry_appended():
    result = _run(CLEAN_TEXT)
    assert len(result["audit_log"]) == 1
    entry = result["audit_log"][0]
    assert entry["node"] == "policy_agent"
    assert entry["action"] == "POLICY_CHECK"
    assert "timestamp" in entry


def test_dpdpa_consent_passes_for_generic_ai_notice():
    """Generic AI disclosure text should not trigger DPDPA_CONSENT."""
    text = (
        "This decision was generated by an AI system operated by First National Bank. "
        "You may request a human review at any time."
    )
    result = _run(text)
    ids = [v["id"] for v in result["policy_result"]["violations"]]
    assert "DPDPA_CONSENT" not in ids


def test_rbi_model_validation_schema_present():
    """RBI_MODEL_VALIDATION must be a recognised criterion ID."""
    from nodes.policy_agent import VALID_IDS
    assert "RBI_MODEL_VALIDATION" in VALID_IDS
    assert "DPDPA_CONSENT" in VALID_IDS
    assert "DPDPA_DATA_MINIMISATION" in VALID_IDS
