"""
tests/test_integration.py
--------------------------
End-to-end integration tests for all three demo scenarios.

Run with: python -m pytest tests/test_integration.py -v
Requires: Ollama running with gemma4:latest pulled
"""

import uuid
import sys
from pathlib import Path

import pytest

sys.path.append(str(Path(__file__).parent.parent))

from graph import app
from state import create_initial_state


# ---------------------------------------------------------------------------
# Test fixtures / shared data
# ---------------------------------------------------------------------------

CLEAN_TEXT = (
    "NOTICE: This assessment was generated by an AI system operated by First National Bank, "
    "the accountable party responsible for this decision. "
    "Outcome: Loan application approved. "
    "Confidence score: 0.87/1.0 — probability the applicant meets lending criteria. "
    "Factors: (1) credit history sourced from internal account records — no missed payments in 36 months; "
    "(2) income stability — consistent for 24+ months; (3) debt-to-income ratio below 35%. "
    "All data is anonymised; no demographic characteristics used. "
    "Limitation: model trained on 2018-2023 data; may underweight non-traditional income. "
    "To appeal, contact First National Bank credit disputes in writing within 30 days. "
    "You may request human review at any time."
)

PII_TEXT = (
    "Dear John Smith, your application reference A-4821 has been reviewed. "
    "Please contact us at john.smith@email.com or call 650-253-0000 "
    "to discuss the outcome of your assessment."
)

DENIAL_TEXT = "Loan application DENIED. Risk score: 0.82. Application ID: APP-7291."

SAMPLE_FEATURES = {
    "age": 34,
    "income": 42000,
    "employment_years": 3,
    "existing_loans": 1,
    "gender": "F",
}


def _config():
    return {"configurable": {"thread_id": str(uuid.uuid4())}}


# ---------------------------------------------------------------------------
# Scenario 1 — Clean compliant input
# ---------------------------------------------------------------------------

def test_scenario_1_clean_input_passes():
    """Well-formed, policy-compliant text should return PASS with no violations."""
    state = create_initial_state(input_type="text", raw_input=CLEAN_TEXT)
    result = app.invoke(state, config=_config())
    assert result["final_status"] == "PASS", f"Expected PASS, got: {result['final_status']}"
    assert result["violations"] == [], f"Expected no violations, got: {result['violations']}"


def test_scenario_1_all_pillar_scores_populated():
    state = create_initial_state(input_type="text", raw_input=CLEAN_TEXT)
    result = app.invoke(state, config=_config())
    scores = result["rai_scores"]
    assert scores is not None
    for key in ["strategic_alignment", "data_governance", "model_governance",
                "org_oversight", "continuous_monitoring"]:
        assert key in scores, f"Missing pillar: {key}"
        assert 0 <= scores[key] <= 3, f"{key} score out of range: {scores[key]}"


# ---------------------------------------------------------------------------
# Scenario 2 — PII leakage
# ---------------------------------------------------------------------------

def test_scenario_2_pii_detected():
    """Text with PII should trigger PII_DETECTED violation."""
    state = create_initial_state(input_type="text", raw_input=PII_TEXT)
    result = app.invoke(state, config=_config())
    assert "PII_DETECTED" in result["violations"], (
        f"Expected PII_DETECTED in violations, got: {result['violations']}"
    )


def test_scenario_2_status_not_pass():
    """PII leakage scenario should never return a clean PASS (corrections happened)."""
    state = create_initial_state(input_type="text", raw_input=PII_TEXT)
    result = app.invoke(state, config=_config())
    assert result["final_status"] != "PASS", (
        f"Unexpected PASS on PII text — PII was not detected or loop bypassed"
    )


# ---------------------------------------------------------------------------
# Scenario 3 — Biased model output
# ---------------------------------------------------------------------------

def test_scenario_3_bias_detected():
    """Model output with biased feature vector should trigger BIAS_DETECTED."""
    state = create_initial_state(
        input_type="model_output",
        raw_input=DENIAL_TEXT,
        feature_vector=SAMPLE_FEATURES,
        protected_attributes=["gender", "age"],
        prediction=0.82,
        predicted_label=1,
    )
    result = app.invoke(state, config=_config())
    assert "BIAS_DETECTED" in result["violations"], (
        f"Expected BIAS_DETECTED in violations, got: {result['violations']}"
    )


def test_scenario_3_bias_metrics_populated():
    """Bias result must contain all three fairness metrics."""
    state = create_initial_state(
        input_type="model_output",
        raw_input=DENIAL_TEXT,
        feature_vector=SAMPLE_FEATURES,
        protected_attributes=["gender", "age"],
        prediction=0.82,
        predicted_label=1,
    )
    result = app.invoke(state, config=_config())
    bias = result.get("bias_result") or {}
    assert bias.get("disparate_impact_ratio") is not None
    assert bias.get("demographic_parity_diff") is not None
    assert bias["disparate_impact_ratio"] < 0.8, (
        f"DI ratio should be < 0.8 for demo model, got: {bias['disparate_impact_ratio']}"
    )


def test_clean_input_passes():
    """Clean input must reach scorecard with PASS status."""
    state = create_initial_state(input_type="text", raw_input=CLEAN_TEXT)
    result = app.invoke(state, config=_config())
    assert result["final_status"] == "PASS"


# ---------------------------------------------------------------------------
# Audit trail
# ---------------------------------------------------------------------------

def test_audit_log_populated():
    """Every run must produce at least 5 audit events (ingestion + 3 agents + scorecard)."""
    state = create_initial_state(input_type="text", raw_input=CLEAN_TEXT)
    result = app.invoke(state, config=_config())
    assert len(result["audit_log"]) >= 5, (
        f"Expected >= 5 audit events, got: {len(result['audit_log'])}"
    )


def test_audit_log_node_names():
    """Audit log must contain entries from all expected nodes."""
    state = create_initial_state(input_type="text", raw_input=CLEAN_TEXT)
    result = app.invoke(state, config=_config())
    nodes = {e["node"] for e in result["audit_log"]}
    for expected in ["ingestion", "pii_agent", "bias_agent", "policy_agent", "scorecard"]:
        assert expected in nodes, f"Missing audit entry for node: {expected}"
